### ISSUE TITLE
Parsing a null value

### ISSUE THREAD

**Issue by manatico4** [Shridhad/jjsonviewer#10]
When I try to parse the following value:

`
{
  "response": {
    "user_profile": {
      "userid": "theOne"
    },
    "jobs_pager": {
      "jobs": [
        {
          "id": 8168881,
          "refcode": null
        }
      ],
      "next_sinceid": "8168881",
      "final_page": false
    }
  }
}
`

 I get the error:
> TypeError: $(...).text(...).html is not a function

Some others values works fine. I guess that the difference is in the "refcode" value.

**Comment by Shridhad** [comment]
Seems to be working fine with me,

<img width="313" alt="screen shot 2016-02-09 at 6 47 07 pm" src="https://cloud.githubusercontent.com/assets/1949852/12911340/975f9adc-cf5d-11e5-90f1-37a7f76239ea.png">


Here is my code

```javascript
var jjson = { "response": { "user_profile": { "userid": "theOne" }, "jobs_pager": { "jobs": [ { "id": 8168881, "refcode": null } ], "next_sinceid": "8168881", "final_page": false } } }

$("#jjson").jJsonViewer(jjson);

```

Could you try verifying that `$` actually points to `jQuery`? I am guessing that might be the issue.
