### ISSUE TITLE
Missing array [ ] when render to html

### ISSUE THREAD

**Issue by dieunt** [Shridhad/jjsonviewer#9]
Hi,

If my input string is an array[ ], when render, it missing [ ].

input = {"contact":[{"name":"a"},{"name":"b"}]}
-> render to html correctly

input = [{"contact":[{"name":"a"},{"name":"b"}]}]
-> render to html without [ and ] 

Thank you.

**Comment by Shridhad** [comment]
Hello @dieunt,

I quickly tried to check the json that you provided, couldn't reproduce the issue. I have attached a screenshot for your reference. 

![screen shot 2015-06-24 at 8 57 44 am](https://cloud.githubusercontent.com/assets/1949852/8322202/5c9f87e0-1a4f-11e5-92ad-e8b2e646d997.png)

I am guessing the styles from your page are messing up with jjsonviewer, It would be great if you could may be you want to check that.
